"""initial_schema

Revision ID: f61c3cd9340b
Revises: 
Create Date: 2026-04-03 13:14:14.635144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61c3cd9340b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('candidate_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tg_user_id', name='uq_candidate_workspace_tg_user_id'),
    sa.UniqueConstraint('workspace_id', 'username', name='uq_candidate_workspace_username')
    )
    op.create_index(op.f('ix_candidate_users_tg_user_id'), 'candidate_users', ['tg_user_id'], unique=False)
    op.create_index(op.f('ix_candidate_users_username'), 'candidate_users', ['username'], unique=False)
    op.create_index(op.f('ix_candidate_users_workspace_id'), 'candidate_users', ['workspace_id'], unique=False)
    op.create_table('collect_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collect_runs_workspace_id'), 'collect_runs', ['workspace_id'], unique=False)
    op.create_table('invite_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'identifier', name='uq_target_workspace_identifier')
    )
    op.create_index(op.f('ix_invite_targets_workspace_id'), 'invite_targets', ['workspace_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('telegram_title', sa.String(length=512), nullable=True),
    sa.Column('telegram_participants_count', sa.Integer(), nullable=True),
    sa.Column('telegram_meta_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collect_mode', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'type', 'identifier', name='uq_source_workspace_type_identifier')
    )
    op.create_index(op.f('ix_sources_workspace_id'), 'sources', ['workspace_id'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_list_tg_user_id'), 'suppression_list', ['tg_user_id'], unique=False)
    op.create_index(op.f('ix_suppression_list_username'), 'suppression_list', ['username'], unique=False)
    op.create_index(op.f('ix_suppression_list_workspace_id'), 'suppression_list', ['workspace_id'], unique=False)
    op.create_table('candidate_source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'candidate_id', 'source_id', name='uq_candidate_source_workspace')
    )
    op.create_index(op.f('ix_candidate_source_links_candidate_id'), 'candidate_source_links', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_source_links_source_id'), 'candidate_source_links', ['source_id'], unique=False)
    op.create_index(op.f('ix_candidate_source_links_workspace_id'), 'candidate_source_links', ['workspace_id'], unique=False)
    op.create_table('invite_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['invite_targets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_runs_target_id'), 'invite_runs', ['target_id'], unique=False)
    op.create_index(op.f('ix_invite_runs_workspace_id'), 'invite_runs', ['workspace_id'], unique=False)
    op.create_table('invite_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('invite_run_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_users.id'], ),
    sa.ForeignKeyConstraint(['invite_run_id'], ['invite_runs.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['invite_targets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_attempts_candidate_id'), 'invite_attempts', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_invite_attempts_invite_run_id'), 'invite_attempts', ['invite_run_id'], unique=False)
    op.create_index(op.f('ix_invite_attempts_target_id'), 'invite_attempts', ['target_id'], unique=False)
    op.create_index(op.f('ix_invite_attempts_workspace_id'), 'invite_attempts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_attempts_workspace_id'), table_name='invite_attempts')
    op.drop_index(op.f('ix_invite_attempts_target_id'), table_name='invite_attempts')
    op.drop_index(op.f('ix_invite_attempts_invite_run_id'), table_name='invite_attempts')
    op.drop_index(op.f('ix_invite_attempts_candidate_id'), table_name='invite_attempts')
    op.drop_table('invite_attempts')
    op.drop_index(op.f('ix_invite_runs_workspace_id'), table_name='invite_runs')
    op.drop_index(op.f('ix_invite_runs_target_id'), table_name='invite_runs')
    op.drop_table('invite_runs')
    op.drop_index(op.f('ix_candidate_source_links_workspace_id'), table_name='candidate_source_links')
    op.drop_index(op.f('ix_candidate_source_links_source_id'), table_name='candidate_source_links')
    op.drop_index(op.f('ix_candidate_source_links_candidate_id'), table_name='candidate_source_links')
    op.drop_table('candidate_source_links')
    op.drop_index(op.f('ix_suppression_list_workspace_id'), table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_username'), table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_tg_user_id'), table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_sources_workspace_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_invite_targets_workspace_id'), table_name='invite_targets')
    op.drop_table('invite_targets')
    op.drop_index(op.f('ix_collect_runs_workspace_id'), table_name='collect_runs')
    op.drop_table('collect_runs')
    op.drop_index(op.f('ix_candidate_users_workspace_id'), table_name='candidate_users')
    op.drop_index(op.f('ix_candidate_users_username'), table_name='candidate_users')
    op.drop_index(op.f('ix_candidate_users_tg_user_id'), table_name='candidate_users')
    op.drop_table('candidate_users')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
